### ISSUE TITLE
Failed to get the ResNet-152 features

### ISSUE THREAD

**Issue by Loycine** [alloldman/CKR#1]
When I tried to run the command:
`wget https://storage.googleapis.com/bringmeaspoon/img_features/ResNet-152-imagenet.zip -O ResNet-152-imagenet.zip`
It returned a 403 error, it said:
`ERROR 403: Forbidden.`
And if I directly visited the website, it returned:
`Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.`

I wonder what should I do to download the data.

**Comment by alloldman** [comment]
Thank you for point out that problem. I have updated the download link in README.
